### ISSUE TITLE
lavf/libplacebo: "Assertion failed: sem_out.sem..." error on Windows

### ISSUE THREAD

**Issue by nyanmisaka** [haasn/libplacebo#127]
Hi! I'm trying to use vf_libplacebo filter in ffmpeg on Windows 10, it fails on AMD cards but works fine on Linux RADV.

`
./ffmpeg -v debug -init_hw_device vulkan=vk:0 -filter_hw_device vk -i R:\Sony_4K60_HDR_Camp.mp4 -an -sn -vf hwupload=derive_device=vulkan,libplacebo=format=nv12 -f null -
`

Error: `Assertion failed: sem_out.sem, file ../src/vulkan/gpu_tex.c, line 1101`
Full log: [amd-windows.txt](https://github.com/haasn/libplacebo/files/8854566/amd-windows.txt)

I've tried ffmpeg latest and 5.0.1 builds from https://github.com/BtbN/FFmpeg-Builds
Drivers and Windows have been upgraded to the latest release.

Any chance you know what causes the issue? (AMD driver, the hwcontext_vulkan in ffmpeg or libplacebo itself)

**Comment by haasn** [comment]
That assertion failing means `AVVkFrame.sem` was an invalid handle at the time of the filter call, apparently.

Any clue on this one? @cyanreg

**Comment by GabeBlincoln** [comment]
I've hit the same thing while attempting to use libplacebo for inverse tonemapping (instead of zscale's less controllable conversion to smpte2084 while setting NPL).  It seems to happen whenever I select certain output formats in FFMPEG itself, although most are rejected...  any RGB output format seems to just error with something about an invalid output pad which seems like an issue on ffmpeg's end since it doesn't mind uploading them.   The >=10-bit YUV formats (I tried most of them with various levels of subsampling) assert or are invalid.  I didn't try the 8bpc formats because I have zero use for them... 

I also get this weirdness when manually enabling the ycbcr conversion extension...   apparently ffmpeg can't find the extension(?) but initializes it later, I'm guessing not because I specified it, along with 4 others that it probably needs for something.

[AVHWDeviceContext @ 0000025e1a1bbdc0] instance extension "VK_KHR_sampler_ycbcr_conversion" not found, excluding.
[AVHWDeviceContext @ 0000025e1a1bbdc0] GPU listing:
[AVHWDeviceContext @ 0000025e1a1bbdc0]     0: AMD Radeon RX 6900 XT (discrete) (0x73af)
[AVHWDeviceContext @ 0000025e1a1bbdc0] Device 0 selected: AMD Radeon RX 6900 XT (discrete) (0x73af)
[AVHWDeviceContext @ 0000025e1a1bbdc0] Queue families:
[AVHWDeviceContext @ 0000025e1a1bbdc0]     0: graphics compute transfer sparse (queues: 1)
[AVHWDeviceContext @ 0000025e1a1bbdc0]     1: compute transfer sparse (queues: 2)
[AVHWDeviceContext @ 0000025e1a1bbdc0]     2: transfer sparse (queues: 2)
[AVHWDeviceContext @ 0000025e1a1bbdc0] Using device extension VK_KHR_sampler_ycbcr_conversion
...

**Comment by nyanmisaka** [comment]
There's no `VK_KHR_sampler_ycbcr_conversion` issue on Vega but the `Assertion failed` issue still exists on Windows.
You can try Mesa RADV on Linux and it should work as expected.

```
[AVHWDeviceContext @ 0000026903bbc840] Supported validation layers:
[AVHWDeviceContext @ 0000026903bbc840]  VK_LAYER_AMD_switchable_graphics
[AVHWDeviceContext @ 0000026903bbc840]  VK_LAYER_VALVE_steam_overlay
[AVHWDeviceContext @ 0000026903bbc840]  VK_LAYER_VALVE_steam_fossilize
[AVHWDeviceContext @ 0000026903bbc840]  VK_LAYER_LUNARG_api_dump
[AVHWDeviceContext @ 0000026903bbc840]  VK_LAYER_LUNARG_device_simulation
[AVHWDeviceContext @ 0000026903bbc840]  VK_LAYER_LUNARG_gfxreconstruct
[AVHWDeviceContext @ 0000026903bbc840]  VK_LAYER_KHRONOS_synchronization2
[AVHWDeviceContext @ 0000026903bbc840]  VK_LAYER_KHRONOS_validation
[AVHWDeviceContext @ 0000026903bbc840]  VK_LAYER_LUNARG_monitor
[AVHWDeviceContext @ 0000026903bbc840]  VK_LAYER_LUNARG_screenshot
[AVHWDeviceContext @ 0000026903bbc840] GPU listing:
[AVHWDeviceContext @ 0000026903bbc840]     0: Radeon RX Vega (discrete) (0x687f)
[AVHWDeviceContext @ 0000026903bbc840] Device 0 selected: Radeon RX Vega (discrete) (0x687f)
[AVHWDeviceContext @ 0000026903bbc840] Queue families:
[AVHWDeviceContext @ 0000026903bbc840]     0: graphics compute transfer sparse (queues: 1)
[AVHWDeviceContext @ 0000026903bbc840]     1: compute transfer sparse (queues: 2)
[AVHWDeviceContext @ 0000026903bbc840]     2: transfer sparse (queues: 2)
[AVHWDeviceContext @ 0000026903bbc840] Using device extension VK_KHR_push_descriptor
[AVHWDeviceContext @ 0000026903bbc840] Using device extension VK_KHR_sampler_ycbcr_conversion
[AVHWDeviceContext @ 0000026903bbc840] Using device extension VK_KHR_synchronization2
[AVHWDeviceContext @ 0000026903bbc840] Using device extension VK_EXT_external_memory_host
[AVHWDeviceContext @ 0000026903bbc840] Using device extension VK_KHR_external_memory_win32
[AVHWDeviceContext @ 0000026903bbc840] Using device extension VK_KHR_external_semaphore_win32
[AVHWDeviceContext @ 0000026903bbc840] Using device: Radeon RX Vega
[AVHWDeviceContext @ 0000026903bbc840] Alignments:
[AVHWDeviceContext @ 0000026903bbc840]     optimalBufferCopyRowPitchAlignment: 1
[AVHWDeviceContext @ 0000026903bbc840]     minMemoryMapAlignment:              64
[AVHWDeviceContext @ 0000026903bbc840]     minImportedHostPointerAlignment:    4096
[AVHWDeviceContext @ 0000026903bbc840] Using queue family 0 (queues: 1) for graphics
[AVHWDeviceContext @ 0000026903bbc840] Using queue family 2 (queues: 2) for transfers
[AVHWDeviceContext @ 0000026903bbc840] Using queue family 1 (queues: 2) for compute
```

**Comment by haasn** [comment]
> I also get this weirdness when manually enabling the ycbcr conversion extension... apparently ffmpeg can't find the extension(?) but initializes it later, I'm guessing not because I specified it, along with 4 others that it probably needs for something.

VK_KHR_sampler_ycbcr_conversion is a **device** extension, not an **instance* extension.

**Comment by diegocr** [comment]
Was this ever reported in trac.ffmpeg.org (also re: https://github.com/haasn/libplacebo/issues/146#issuecomment-1292497234) ?

I'm on Windows 11 using an RTX A5500 and started experiencing this recently...i think (i.e. ffmpeg does hangs for me after printing `AVHWDeviceContext @ ....] Using queue family 1 (queues: 2) for compute` as pointed in the above comment)

However, what i can assure is that this only started happening here on Nov 17 (keeping backups of each daily build), but... issuing a `git reset --hard 27e38da9ee133d` and rebuilding both libplacebo and ffmpeg the same issue does persist.

Sorry for this kind of vague report/comment, happy to provide further details - just looking for thoughts about what could be going on here.

**Comment by haasn** [comment]
On current FFmpeg git master you can skip the `hwupload/hwdownload` steps, maybe that helps avoid this issue.

**Comment by diegocr** [comment]
Thanks for the hint, didn't knew about that.

Just gave it a try and i'm afraid it does still crashed.

```log
$ ffmpeg.exe -hwaccel cuda -i "%INPUT%" -vf "hwupload=derive_device=vulkan,libplacebo=tonemapping=hable:format=yuv420p,hwupload=derive_device=cuda" -c:v hevc_nvenc -an -v trace -y "%OUTPUT%"

ffmpeg version N-109252-gab5f34b761-g48c385fb4c+1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.2.0 (Rev6, Built by MSYS2 project)
  configuration:  ....
...
[Parsed_hwupload_0 @ 000001c3962d6e00] Setting 'derive_device' to value 'vulkan'
[Parsed_libplacebo_1 @ 000001c3962d7600] Setting 'tonemapping' to value 'hable'
[Parsed_libplacebo_1 @ 000001c3962d7600] Setting 'format' to value 'yuv420p'
[libplacebo @ 000001c3c1468880] Initialized libplacebo v5.229.1-35-gb9ad142 (API v233)
[Parsed_hwupload_2 @ 000001c3962d7c00] Setting 'derive_device' to value 'cuda'
[graph 0 input from stream 0:0 @ 000001c3962d7b00] Setting 'video_size' to value '1920x804'
[graph 0 input from stream 0:0 @ 000001c3962d7b00] Setting 'pix_fmt' to value '23'
[graph 0 input from stream 0:0 @ 000001c3962d7b00] Setting 'time_base' to value '1/1000'
[graph 0 input from stream 0:0 @ 000001c3962d7b00] Setting 'pixel_aspect' to value '1/1'
[graph 0 input from stream 0:0 @ 000001c3962d7b00] Setting 'frame_rate' to value '24000/1001'
[graph 0 input from stream 0:0 @ 000001c3962d7b00] w:1920 h:804 pixfmt:nv12 tb:1/1000 fr:24000/1001 sar:1/1
[format @ 000001c3962d6a00] Setting 'pix_fmts' to value 'yuv420p|nv12|p010le|yuv444p|p016le|yuv444p16le|bgr0|bgra|rgb0|rgba|x2rgb10le|x2bgr10le|gbrp|gbrp16le|cuda|d3d11'
[AVHWDeviceContext @ 000001c395ccebc0] Calling cu->cuDeviceGetUuid((CUuuid *)&dev_select.uuid, cu_internal->cuda_device)
[AVHWDeviceContext @ 000001c3ad760640] Supported validation layers:
[AVHWDeviceContext @ 000001c3ad760640]  VK_LAYER_NV_optimus
[AVHWDeviceContext @ 000001c3ad760640] GPU listing:
[AVHWDeviceContext @ 000001c3ad760640]     0: NVIDIA RTX A5500 Laptop GPU (discrete) (0x2438)
[AVHWDeviceContext @ 000001c3ad760640]     1: Intel(R) UHD Graphics 770 (integrated) (0x4688)
[AVHWDeviceContext @ 000001c3ad760640] Device 0 selected: NVIDIA RTX A5500 Laptop GPU (discrete) (0x2438)
[AVHWDeviceContext @ 000001c3ad760640] Queue families:
[AVHWDeviceContext @ 000001c3ad760640]     0: graphics compute transfer sparse (queues: 16)
[AVHWDeviceContext @ 000001c3ad760640]     1: transfer sparse (queues: 2)
[AVHWDeviceContext @ 000001c3ad760640]     2: compute transfer sparse (queues: 8)
[AVHWDeviceContext @ 000001c3ad760640]     3: transfer sparse (queues: 1)
[AVHWDeviceContext @ 000001c3ad760640] Using device extension VK_KHR_push_descriptor
[AVHWDeviceContext @ 000001c3ad760640] Using device extension VK_KHR_sampler_ycbcr_conversion
[AVHWDeviceContext @ 000001c3ad760640] Using device extension VK_KHR_synchronization2
[AVHWDeviceContext @ 000001c3ad760640] Using device extension VK_EXT_external_memory_host
[AVHWDeviceContext @ 000001c3ad760640] Using device extension VK_KHR_external_memory_win32
[AVHWDeviceContext @ 000001c3ad760640] Using device extension VK_KHR_external_semaphore_win32
[AVHWDeviceContext @ 000001c3ad760640] Using device: NVIDIA RTX A5500 Laptop GPU
[AVHWDeviceContext @ 000001c3ad760640] Alignments:
[AVHWDeviceContext @ 000001c3ad760640]     optimalBufferCopyRowPitchAlignment: 1
[AVHWDeviceContext @ 000001c3ad760640]     minMemoryMapAlignment:              64
[AVHWDeviceContext @ 000001c3ad760640]     minImportedHostPointerAlignment:    4096
[AVHWDeviceContext @ 000001c3ad760640] Using queue family 0 (queues: 16) for graphics
[AVHWDeviceContext @ 000001c3ad760640] Using queue family 1 (queues: 2) for transfers
[AVHWDeviceContext @ 000001c3ad760640] Using queue family 2 (queues: 8) for compute
```

Removing `hwupload` there (and w&w/o using `-init_hw_device "vulkan=gpu:0/1"` etc) the crash does occur right before printing the `AVHWDeviceContext` lines (around the same place i guess)

Well, i'll keep waiting for FFmpeg devs to fix this, i think i must not be alone here therefore someone else facing the same issue and more familiar with bisecting/reporting this kind of bugs will submit it later or sooner, or so i hope.

**Comment by haasn** [comment]
@diegocr oh, sorry, I meant the original issue, not yours. You seem to have a completely different bug.

**Comment by diegocr** [comment]
Doh! haha. Okay, no problem, all good :)

**Comment by Chipcraft** [comment]
Pleased to report that the original issue occurring on AMD graphics cards is solved by the master branch of FFMpeg (currently 3b66757d7d12b21c7717ccb4459f3913fa3b8d0d).

The previous method involving hwupload & hwupload does still fail with the current drivers (Adrenalin 22.11.2 WHQL and 22.12.1) however, using the master branch of FFMpeg and omitting hwupload & hwdownload does the trick. 

Tested on RDNA2 and RDNA3 GPUs.

**Comment by haasn** [comment]
Then closing here for now, as the other issue is not a libplacebo bug.

**Comment by NeedsMoar** [comment]
Removing hwupload / hwdownload worked on Vega too.  I don't know what implicit hwdownload does to the ability to chain together vulkan filters or if ffmpeg handles this internally.  I tested with an older ffmpeg version on Vega and a newer on 7900XTX in February with a recent build.  A _format=p010_ filter argument was required when inverse tonemapping and outputting to a yuv420p10le pix_fmt as well or other errors occured, for some reason the output format wasn't being inferred properly from a separate format filter or the implicitly inserted one generated by a -pix_fmt  argument.  (Or the input from that matter, when I up-converted to 10bpc first)  Just in case anyone else sees this.   

There was no way to control peak and the colorspace conversion seemed to be wrong, as if it was using a smaller colorspace as input than what was actually there (maybe this needs to be explicitly forced elsewhere or the pixel format converted to something else on the input side, I don't know) but it produced an hdr10 video that madmeasurehdr reported as having a maxCLL of around 10k after inverse tonemapping so that's some progress.
