### ISSUE TITLE
Rendering zero copy HDR AVFrames decoded via Vulkan (NVidia GPU) results in green frames

### ISSUE THREAD

**Issue by streamingdv** [haasn/libplacebo#237]
Hi,

currently I'm working on a Java wrapper for libplacebo to render my real time stream. So far everythin works great and I'm currently testing it on my Windows development machine. My application supports DXVA, D3D11, NVIDEO_CUDA and VULKAN decoding on Windows. As far as I have understood the source code of libplacebo, AVFrames decoded via Vulkan, VAAPI are supporting zero copy rendering via libplacebo (when VkWin32SurfaceCreateInfoKHR is used on Windows for example). However, I encountered a strange problem during testing and I'm not sure if it's a driver issue, ffmpeg issue, or libplacebo issue. I have following results on my Windows machine:

H264 decoding

SOFTWARE decoding + libplacebo rendering = ✓
NVIDEO_CUDA decoding + libplacebo rendering = ✓
DXVA decoding + libplacebo rendering = ✓
D3D11 decoding + libplacebo rendering = ✓
VULKAN decoding + libplacebo rendering = ✓
VULKAN decoding (zero copy)+ libplacebo rendering = ✓

H265 decoding

SOFTWARE decoding + libplacebo rendering = ✓
NVIDEO_CUDA decoding + libplacebo rendering = ✓
DXVA decoding + libplacebo rendering = ✓
D3D11 decoding + libplacebo rendering = ✓
VULKAN decoding + libplacebo rendering = ✓
VULKAN decoding (zero copy)+ libplacebo rendering = ✓

H265 + HDR10 decoding

SOFTWARE decoding + libplacebo rendering = ✓
NVIDEO_CUDA decoding + libplacebo rendering = ✓
DXVA decoding + libplacebo rendering = ✓
D3D11 decoding + libplacebo rendering = ✓
VULKAN decoding + libplacebo rendering = ✓
**VULKAN decoding (zero copy)+ libplacebo rendering = ✗ (green frames)**

The only difference I do when when using zero copy is this

        if (this.m_VideoDecoderCtx.hw_device_ctx() == null || !hwDownload) {
            decodedFrame = avFrame; // use the frame as is for Software frames an zero copy
        } else {
            final AVFrame hwAvFrame = av_frame_alloc();
            if (av_hwframe_transfer_data(hwAvFrame, avFrame, 0) < 0) {
                av_frame_unref(hwAvFrame);
                decodedFrame = avFrame;
            } else {
                av_frame_unref(avFrame);
                decodedFrame = hwAvFrame;
            }
        }

        return decodedFrame;

When I use vulkan decoding without the  zero copy via `av_hwframe_transfer_data` and pass this frame to libplacebo everything works fine. But with zero copy I get only greenish frames and via the log I get following warnings, errors

`Masking `blit_src` from wrapped texture because the corresponding format 'rx10' does not support PL_FMT_CAP_BLITTABLE`

I'm not sure if [this issue](https://github.com/haasn/libplacebo/issues/178) is related but it sounds similar. Here is an example frame to visualize what I mean with "green frame"

![geen](https://github.com/haasn/libplacebo/assets/123362466/3514e1b0-8366-44bd-b1f6-3af39e5b463c)

normal hdr via VULKAN decoding + libplacebo rendering

![normal](https://github.com/haasn/libplacebo/assets/123362466/ed819d2b-3e08-4383-905f-d666a412c1ab)

This is how I get the AVFrame and this is how I pass it to libplacebo

        AVFrame avFrame = videoDecoder.decodeFrame(isKeyFrame, frameByteBuffer.limit(), hwDownload); // hwDownload is false for Vulkan + HDR
        boolean result = this.placeboManager.plRenderAvFrame(avFrame.address(), this.placeboVulkan, this.placebo_swapchain,     this.placebo_renderer);

And in my JNI code I do follwowing

```
extern "C"
JNIEXPORT jboolean JNICALL Java_com_grill_placebo_PlaceboManager_plRenderAvFrame
  (JNIEnv *env, jobject obj, jlong avframe, jlong placebo_vulkan, jlong swapchain, jlong renderer) {
  AVFrame *frame = reinterpret_cast<AVFrame*>(avframe);
  pl_vulkan vulkan = reinterpret_cast<pl_vulkan>(placebo_vulkan);
  pl_swapchain placebo_swapchain = reinterpret_cast<pl_swapchain>(swapchain);
  pl_renderer placebo_renderer = reinterpret_cast<pl_renderer>(renderer);

  pl_tex placebo_tex[4] = {nullptr, nullptr, nullptr, nullptr};
  struct pl_swapchain_frame sw_frame = {0};
  struct pl_frame placebo_frame = {0};
  struct pl_frame target_frame = {0};

  struct pl_avframe_params avparams = {
      .frame = frame,
      .tex = placebo_tex,
      .map_dovi = false,
  };
  bool mapped = pl_map_avframe_ex(vulkan->gpu, &placebo_frame, &avparams);

  if (!mapped) {
      LogCallbackFunction(nullptr, PL_LOG_ERR, "Failed to map AVFrame to Placebo frame!");
      return false;
  }
  // set colorspace hint
  struct pl_color_space hint = placebo_frame.color;
  pl_swapchain_colorspace_hint(placebo_swapchain, &hint);

  pl_rect2df crop;
  bool ret = false;
  pl_render_params render_params = pl_render_fast_params; // pl_render_high_quality_params, pl_render_default_params

  if (!pl_swapchain_start_frame(placebo_swapchain, &sw_frame)) {
      LogCallbackFunction(nullptr, PL_LOG_ERR, "Failed to start Placebo frame!");
      goto cleanup;
  }

  pl_frame_from_swapchain(&target_frame, &sw_frame);

  crop = placebo_frame.crop;
  if (!pl_render_image(placebo_renderer, &placebo_frame, &target_frame, &render_params)) {
      LogCallbackFunction(nullptr, PL_LOG_ERR, "Failed to render Placebo frame!");
      goto cleanup;
  }
  if (!pl_swapchain_submit_frame(placebo_swapchain)) {
      LogCallbackFunction(nullptr, PL_LOG_ERR, "Failed to submit Placebo frame!");
      goto cleanup;
  }
  pl_swapchain_swap_buffers(placebo_swapchain);
  ret = true;

cleanup:
  pl_unmap_avframe(vulkan->gpu, &placebo_frame);

  return ret;
}
```

Here is a [full example](https://gist.github.com/streamingdv/48ba41d16527453bdea924bc0bf6dc9a) of my JNI wrapper code.
Is this something which is known? If not I can provide more information.

I have a reproducable java rendering project which uses [javacv](https://github.com/bytedeco/javacv) for the ffmepg decoding part and my libplacebo java wrapper for the rendering part. If needed I can upload this example to my GitHub account.

**Comment by nowrep** [comment]
Try this https://github.com/haasn/libplacebo/pull/239

**Comment by streamingdv** [comment]
@nowrep thanks I will try it out later this week, was in contact jbaiter and he told me about this. Was not aware that there is an open pull request for that. I really hope that this fixes the issue.

**Comment by streamingdv** [comment]
@haasn just for information the fix in the pull request

"Only adjust bit_shift for DRM P010 frames"

Mentioned above, fixed the problem for me.

**Comment by gitoss** [comment]
I'm reportg this issue occurs with AMD, too - I'm on Ryzen 7540U w/ RDNA3 740M, Driver 23.11.1 (newer Adrenaline versions have a horrible memory leak bug).

`ffmpeg -hwaccel vulkan -hwaccel_output_format vulkan -an -i %INPUT% -vf "hwupload,libplacebo=peak_detect=true:tonemapping=hable:colorspace=bt709:color_primaries=bt709:color_trc=bt709:gamut_mode=desaturate:format=nv12,hwdownload,format=nv12" -f null - -benchmark`

Works fine for sdr sources, but just like described on the op breaks with hdr sources on current ffmpeg versions - error output below. This is very relevant to me, because Vulkan decoding (i.e. zero copy) is 2x fps of software decoding. Hardware decode with dxva2/d3d11va is only 1.5 fps of software decoding.

I tried to track when the change occurs - it was beween 2023-04-30 and 2023-05-31 becuse it works up to "ffmpeg version N-111869-g7aa71ab5c0-20230831", but starts to be buggy with "ffmpeg version N-110422-g7b2851b290-20230430" and later. https://github.com/BtbN/FFmpeg-Builds/releases

_[libplacebo @ 000000001d8ee4c0] Masking sampleable from wrapped texture because the corresponding format 'rx10' does not support PL_FMT_CAP_SAMPLEABLE
[libplacebo @ 000000001d8ee4c0] Masking blit_src from wrapped texture because the corresponding format 'rx10' does not support PL_FMT_CAP_BLITTABLE
[libplacebo @ 000000001d8ee4c0] Masking sampleable from wrapped texture because the corresponding format 'rxgx10' does not support PL_FMT_CAP_SAMPLEABLE
[libplacebo @ 000000001d8ee4c0] Masking blit_src from wrapped texture because the corresponding format 'rxgx10' does not support PL_FMT_CAP_BLITTABLE
[libplacebo @ 000000001d8ee4c0] Masking sampleable from wrapped texture because the corresponding format 'rx10' does not support PL_FMT_CAP_SAMPLEABLE
[libplacebo @ 000000001d8ee4c0] Masking blit_src from wrapped texture because the corresponding format 'rx10' does not support PL_FMT_CAP_BLITTABLE
[libplacebo @ 000000001d8ee4c0] Masking sampleable from wrapped texture because the corresponding format 'rxgx10' does not support PL_FMT_CAP_SAMPLEABLE
[libplacebo @ 000000001d8ee4c0] Masking blit_src from wrapped texture because the corresponding format 'rxgx10' does not support PL_FMT_CAP_BLITTABLE
[libplacebo @ 000000001d8ee4c0] Validation failed: (image->planes[i]).texture->params.sampleable (src/renderer.c:2704)
[libplacebo @ 000000001d8ee4c0] Backtrace:
[libplacebo @ 000000001d8ee4c0] #0 0x7ff66c7a7b9f in FT_Set_Default_Log_Handler+0xaa9df (ffmpeg.exe+0x14e7b9f) (0x1414e7b9f)
[libplacebo @ 000000001d8ee4c0] #1 0x7ff66c7ab6c8 in pl_render_image+0xa8 (ffmpeg.exe+0x14eb6c8) (0x1414eb6c8)
[libplacebo @ 000000001d8ee4c0] #2 0x7ff66c7acb63 in pl_render_image_mix+0x1383 (ffmpeg.exe+0x14ecb63) (0x1414ecb63)
[libplacebo @ 000000001d8ee4c0] #3 0x7ff66b42173c (ffmpeg.exe+0x16173c) (0x14016173c)
[libplacebo @ 000000001d8ee4c0] #4 0x7ff66b42269a (ffmpeg.exe+0x16269a) (0x14016269a)
[libplacebo @ 000000001d8ee4c0] #5 0x7ff66b32888b (ffmpeg.exe+0x6888b) (0x14006888b)
[libplacebo @ 000000001d8ee4c0] #6 0x7ff66b32d62f (ffmpeg.exe+0x6d62f) (0x14006d62f)
[libplacebo @ 000000001d8ee4c0] #7 0x7ff66b2d338f (ffmpeg.exe+0x1338f) (0x14001338f)
[libplacebo @ 000000001d8ee4c0] #8 0x7ff66b2ec158 (ffmpeg.exe+0x2c158) (0x14002c158)
[libplacebo @ 000000001d8ee4c0] #9 0x7ff66cf924ca in FT_Get_PS_Font_Value+0x8229a (ffmpeg.exe+0x1cd24ca) (0x141cd24ca)
[libplacebo @ 000000001d8ee4c0] #10 0x7ff83eefe633 in beginthreadex+0x133 (C:\Windows\System32\msvcrt.dll+0x3e633) (0x11013e633)
[libplacebo @ 000000001d8ee4c0] #11 0x7ff83eefe70b in endthreadex+0xab (C:\Windows\System32\msvcrt.dll+0x3e70b) (0x11013e70b)
[libplacebo @ 000000001d8ee4c0] #12 0x7ff83e19257c in BaseThreadInitThunk+0x1c (C:\Windows\System32\KERNEL32.DLL+0x1257c) (0x18001257c)
[libplacebo @ 000000001d8ee4c0] #13 0x7ff83ff8aa47 in RtlUserThreadStart+0x27 (C:\Windows\SYSTEM32\ntdll.dll+0x5aa47) (0x18005aa47)_
