### ISSUE TITLE
Does libplacebo support custom transition effect shader？

### ISSUE THREAD

**Issue by HuHeng** [haasn/libplacebo#252]
I would like to inquire whether libplacebo's custom shader supports this scenario, blending two video streams using a custom shader to achieve some blend effects, such as transition effects, which require manipulating the textures of these two sources. It seems that the stages and hooks defined within the custom shader are only for one input source? I am not sure if my understanding is correct.

**Comment by haasn** [comment]
Indeed, inside libplacebo, `pl_renderer` is tied to a single video source. (It maintains frame mixing state, tone mapping state, and so on - having separate video streams would break this abstraction quite badly)

I can see some potential paths for this feature to exist, but I would like to know a bit more about your use case - are you using libplacebo inside your own application (C), are you using it inside ffmpeg, or are you using it inside mpv? Because handling multiple input streams will require *some* support from the wrapping application, and if it's your own code it might be easier to just handle it in C using `pl_shader_custom`.

**Comment by HuHeng** [comment]
Thank you very much for your answer. I am in the research phase, and if used, it should be used in my own C program.

**Comment by Hlongyu** [comment]
Same question. It's seem custom shader only support one texture input. How can i use two textures?   


It's there any way to render ffmpeg frame to custom opengl texture?     

So i can do it like:   
ffmpeg_frame->libplacebo->rgba_texture->custom_shader-> custom_render

**Comment by Hlongyu** [comment]
> So i can do it like:
> ffmpeg_frame->libplacebo->rgba_texture->custom_shader-> custom_render  

use pl_opengl_wrap() to upload rgba_texture.
