### ISSUE TITLE
how to build for armv7 & arm64 on iPhone

### ISSUE THREAD

**Issue by idoit** [haasn/libplacebo#44]
Hi, I see vlc use this code, and it can build using Makefile.
I want to build the lib for armv7 and arm64, I use this ：
CC="$(xcrun --sdk iphoneos --find clang) -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -arch arm64 -arch armv7" make
but , that don't work.

the Makefile is below:
SRCS := colorspace.c common.c context.c dither.c dispatch.c filters.c renderer.c shaders.c \
	shaders/colorspace.c shaders/sampling.c spirv.c bstr/bstr.c bstr/format.c 3rdparty/siphash.c \
	ta/ta.c ta/ta_utils.c ta/talloc.c

lpthread_libs = $(shell $(LD) -lpthread && echo "-lpthread" || echo "")

OBJS = $(patsubst %.c, $(OBJDIR)src/%.o, $(SRCS))

CFLAGS += -D_ISOC99_SOURCE -D_GNU_SOURCE \
	-Isrc -Isrc/osdep -Isrc/include \
	-fvisibility=hidden -Wall -Wundef -Wmissing-prototypes -Wshadow \
	-Wparentheses -Wpointer-arith -Wno-pointer-sign

targets = libplacebo.a

all: $(targets)

install: $(targets)
	rm -rf $(PREFIX)/include/libplacebo
	mkdir -p $(PREFIX)/lib/pkgconfig/ $(PREFIX)/include/libplacebo
	cp -r src/include/libplacebo $(PREFIX)/include
	cp src/config.h $(PREFIX)/include/libplacebo
	cp libplacebo.a $(PREFIX)/lib/
	@echo "Name: libplacebo" > $(PREFIX)/lib/pkgconfig/libplacebo.pc
	@echo "Description: Reusable library for GPU-accelerated video/image rendering" >> $(PREFIX)/lib/pkgconfig/libplacebo.pc
	@echo "Version: 0.2.1" >> $(PREFIX)/lib/pkgconfig/libplacebo.pc
	@echo "Libs: -L$(PREFIX)/lib -lplacebo $(lpthread_libs)" >> $(PREFIX)/lib/pkgconfig/libplacebo.pc
	@echo "Cflags: -I$(PREFIX)/include" >> $(PREFIX)/lib/pkgconfig/libplacebo.pc

$(OBJDIR)/%.o: src/%.c
	$(CC) -c $(CFLAGS) $< -o $@

libplacebo.a: $(OBJS)
	$(AR) csr $@ $^

clean:
	rm -f *.o
	rm -f $(targets)

**Comment by haasn** [comment]
What error message do you get? Also, I don't really know anything about iOS/iPhone compilation so I'm not sure I will be able to help much.

iirc @ePirat has done some compilation on macOS, maybe it's similar

**Comment by idoit** [comment]
thank you for your reply。 there are no compile error, but when i use the library, then will get error below:
Undefined symbols for architecture arm64:
  "_ra_tex_create", referenced from:

**Comment by haasn** [comment]
Have you tried using meson to cross compile instead of doing it by hand?

Also, `v0.2.1` is not recommended unless you have a really good reason to stay on that old version. That's pretty much just a bug fix release for VLC 3.0, and is still an early alpha build of libplacebo that has many features missing. If you are not specifically trying to build VLC 3.0, you should use a newer version if at all possible. (And even if you are doing this for VLC, I'm not sure if the opengl sw vout will even do anything for iOS)

**Comment by ePirat** [comment]
To cross compile with meson, [as described in the documentation](https://mesonbuild.com/Cross-compilation.html), you need to provide a cross file, for example:

```
[binaries]
c = 'clang'
ar = 'ar'
strip = 'strip'

[properties]
c_args = ['-arch', 'armv7', '-miphoneos-version-min=12.0', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk']
cpp_args = ['-arch', 'armv7', '-miphoneos-version-min=12.0', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk']
c_link_args = ['-arch', 'armv7', '-miphoneos-version-min=12.0', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk']
cpp_link_args = ['-arch', 'armv7', '-miphoneos-version-min=12.0', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk']

[host_machine]
system = 'darwin'
cpu_family = 'arm'
cpu = 'armv7'
endian = 'little'
```

Adapt and save this somewhere, then call meson like that:

```
meson build --cross-file ios_cross_armv7.txt
```

**Comment by haasn** [comment]
Also as for the actual error, I think what might be happening is that the makefile you're using specifies `shaders/sampling.c` but doesn't specify `ra.c`, which the former depends on. So either add `ra.c` (+ its dependencies, if it has any) to the list of sources to compile or remove `shaders/sampling.c` (which I believe VLC 3.0 doesn't use anyway).

Most likely this was not caught during testing because other platforms don't generate link errors for unresolved symbols at build time? You could possibly work around this by adding the appropriate "laziness" flag to the build, i.e. `-Wl,-z,lazy` for gcc.

**Comment by idoit** [comment]
thanks, i solve the problem. because the make file lost the gnu.c
