### ISSUE TITLE
gentoo ebuild doesn´t work

### ISSUE THREAD

**Issue by jsffm** [haasn/libplacebo#48]
Use attached patch
[ebuild.diff.gz](https://github.com/haasn/libplacebo/files/2550045/ebuild.diff.gz)

**Comment by jsffm** [comment]
An other error, patch includes both changes:
[ebuild2.diff.gz](https://github.com/haasn/libplacebo/files/2550211/ebuild2.diff.gz)

**Comment by haasn** [comment]
Sorry, I sort of got side-tracked on the ebuild since this was blocked ebuild and forgot to update the one in the repo. I've deleted it and replaced it by a link to the `gentoo-gpu` one instead, which I will be keeping up-to-date until it is [merged upstream](https://github.com/gentoo/gentoo/pull/10006)
