### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#56]
After implementing the library in my project I still have some minor questions on using it.
1. Your default lightscene for BT709 is PL_COLOR_LIGHT_DISPLAY.  Isn't PL_COLOR_LIGHT_SCENE_709_1886  the correct one ?

2. When using  pl_render_image does it presacle the UV plane before converting the colors to RGB ? 
If not what scaler could I use to do this beforehand ? 

3. Do you plan to provide more shaders e.g. for sharpening, denoising, etc ?

4. Have you read about the Darbee Picture Optimization (http://www.darbeevision.com/technology-briefs/). Would it be possible to write a shader for this ?

**Comment by haasn** [comment]
1. It's tricky. In the actual BT.709 definition, the OOTF is assumed to be part of the OETF, i.e. the producer of the content has already applied the scene->display transition. In effect, it happens implicitly due to the fact that BT.709-produced content is meant to be decoded by BT.1886 (*not* the inverse BT.709, as is often mis-assumed!). From the point of view of libplacebo, which (due to its historical background from being part of the mpv video output driver) only considers the EOTF and nothing else, what we're actually dealing with is more easily modelled by BT.1886 content in display-referred light. Or, put another way, we could either treat BT.709 content as having transfer=BT_709, light=SCENE_709_1886, or we could treat it as having transfer=BT_1886, light=DISPLAY, which is what we do.

The reason we did things this way is because, first of all, mpv had BT.1886 long before it had support for custom OOTFs; and secondly, because we want the BT.1886 curve implementation to be baked into the 3DLUT when using ICC-based color management, for efficiency. (But it might be worth investigating how much that really matters)

That being said, we might also want to introduce the concept of a "black point" in the colorimetriy metadata, and then handle the OOTF in generic shader code. That way we can correctly adapt the BT.1886 transfer function to a monitor with fixed contrast (say 1000:1) without requiring an ICC profile, and also decouple the BT.1886 handling from the ICC profile code.

2. Yes, it will upscale any planes to match the size of the biggest one, using the same scale you configured in `pl_render_params.upscaler`.

3. I could add some simple shaders for these if you need them. Any specific requests?

4. Depends on the algorithm. I don't see any source code or algorithm description in a quick glance of the white paper. If you can find one, ask me again.

**Comment by jojo61** [comment]
1. After reading some stuff about Color managment I now understand your reply much better.  I think your approach to decouple BT.1886 fron ICC handling is sensible and I support your idea to introduce the concept of a "black point". That way BT.1886 could be adopted for different monitor settings (e.g. LCD oder Beamer with different "black" levels). Also ICC Profiles are not always available and hard to generate.

2. Great

3. I have currently no urgent need for additional scalers, but a unsharp mask would be nice.  Having said that it would also be nice if pl_render_image would provide one or more additional shader steps. Currently it does 3 things 1.Convert input Image to RGB Color, 2. Scale 3. Convert RGB Image to Target Color. It would be nice if one could include more shader steps in that queue. So if you could extent the pl_render_params to include a list of additional shader steps, that would be nice. Of cource this could be done by the User with Tier 3 commands, but in Tier 4 it is not possible.

**Comment by haasn** [comment]
Great idea for 3. I have no idea why I didn't think of it before. Yes, it would be very easy for us to extend the `pl_render_params` with a "hooks" style of extra shaders to run using the `pl_shader` API. In fact, that's the whole reason this API exists!

The only thing we'd need on top of that is the ability to include "custom" functions in `pl_shader`, but a clean API for that should be reasonable. With all that in place, it should be possible to allow the user to specify arbitrary extra shaders.

Actually, it might be time to think about opening up all of the internel helper goodies we use to generate `pl_shader`s to the wide world (e.g. `pl_var`, `pl_desc`, ...).

**Comment by haasn** [comment]
We should also add something like `pl_shader_convolve` to implement a fixed (hard coded) convolution mask, that way an unsharp mask would be easy. (And we could provide them as examples of convolution tables)

**Comment by haasn** [comment]
Oh, I actually did have an open issue for 3: #19

**Comment by jojo61** [comment]
#19  is more about the shader hook to implement external shaders.  I talked about the existing shaders initialy, but of course external shaders would be even better.
