### ISSUE TITLE
Gammasetting has no effect

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#68]
struct pl_color_adjustment {
    // Brightness boost. 0.0 = neutral, 1.0 = solid white, -1.0 = solid black
    float brightness;
    // Contrast boost. 1.0 = neutral, 0.0 = solid black
    float contrast;
    // Saturation gain. 1.0 = neutral, 0.0 = grayscale
    float saturation;
    // Hue shift, corresponding to a rotation around the [U, V] subvector, in
    // radians. Only meaningful for YCbCr-like colorspaces. 0.0 = neutral
    float hue;
    // Gamma adjustment. 1.0 = neutral, 0.0 = solid black
    float gamma;
};

Changing the gamma value has no effect. Is this not implemented or do I need to set some other things as well to see an effect. When setting gamma to anything other than 1.0 it shows no effect.

**Comment by haasn** [comment]
You're right, it's completely unimplemented. Thinking about this, I noticed actually that the gamma adjustment being part of this struct makes little sense because of where in the rendering pipeline we'd need to apply gamma. If we want to do it in linear light, then it requires doing it after linearization, which is a completely separate step from the color decoding phase which is where the rest of those parameters come into play.

Alternatively, we could just do it immediately after color adjustment, which means the gamma adjustment will be done non-linearly, which may have undesirable effects. But I think since the purpose of this setting is "aesthetic adjustment" rather than targetting any precise values (for those we have the color management system), that might be an acceptable trade-off for code simplicity.

I feel like this is the path I'll take for now. Thanks for reporting it!
