### ISSUE TITLE
Interpolation branch status

### ISSUE THREAD

**Issue by Ichunjo** [haasn/libplacebo#85]
Hello, 
Can I find out the current state of the interpolation branch?
I haven't seen any new commits in quite some time :/

**Comment by haasn** [comment]
[This commit](https://code.videolan.org/videolan/libplacebo/-/commit/ba503f5466da555d1b0caa3a0855c152552467d7) summarizes the current status. It's not entirely stalled, but the difficult part that I've been avoiding is coming up with a good way of testing the interpolation code. (Currently, none of the libplacebo API users have the necessary frame queue in order to give us all the information needed to interpolate images properly. I'll have to write a dedicated test program that uses hard-coded weights or something, but that's much harder to evaluate than "watching" it in motion)

Anyway, the current status of libplacebo in general is that I'm still out of commission and will be for another month or so at the minimum, so don't expect any/much progress until then.
