### ISSUE TITLE
DRM_FORMAT_MOD_INVALID   not handled

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#92]
Hi

in src/gpu.c  in function check_mod  you do not handle DRM_FORMAT_MOD_INVALID. This should be accepted as valid format.

I need to set DRM_FORMAT_MOD_INVALID with the opengl Version in order to not set ADD_DMABUF_PLANE_MODIFIERS(0, shared_mem->drm_format_mod); in opengl/gpu.c.

**Comment by haasn** [comment]
What modifiers are supposed by your format? Why can't you use one of those?

**Comment by jojo61** [comment]
If I try with DRM_FORMAT_MOD_INVALID and you unpatched libplacebo I get the following message:
Validation failed: (image->planes[i]).texture (../src/renderer.c:1956)
error: DRM modifier INVALID not available for format r8. Available modifiers:
error:     LINEAR
error:     INTEL 0x1
error:     INTEL 0x2

If I then try to use DRM_FORMAT_MOD_LINEAR then the picture is distorted and it seems that the dma is handled wrong.
Same with DRM_FORMAT_MOD_VENDOR_INTEL or DRM_FORMAT_MOD_VENDOR_AMD.  If I remove in opengl/gpu.c the settig of the DMABUF_PLANE_MODIFIERS then everything is ok as well. So the problem is to set  the DMABUF_PLANE_MODIFIER.  Below is the function to set the DMA Buffer from VAAPI decoder result to the Textures.

Sorry for the lengthy post.

void generateVAAPIImage(CuvidDecoder * decoder, int index, const AVFrame * frame, int image_width, int image_height)
{
    int n;
    VAStatus status;
    int toggle = 0;
    uint64_t first_time;
    VADRMPRIMESurfaceDescriptor desc;

    status =
        vaExportSurfaceHandle(decoder->VaDisplay, (unsigned int)frame->data[3], VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME_2,
        VA_EXPORT_SURFACE_READ_ONLY | VA_EXPORT_SURFACE_SEPARATE_LAYERS, &desc);

    if (status != VA_STATUS_SUCCESS) {
        printf("Fehler beim export VAAPI Handle\n");
        return;
    }
    vaSyncSurface(decoder->VaDisplay, (unsigned int)frame->data[3]);
    Lock_and_SharedContext;
    for (n = 0; n < 2; n++) {           //  Set DMA_BUF from VAAPI decoder to Textures
        int id = desc.layers[n].object_index[0];
        int fd = desc.objects[id].fd;
        uint32_t size = desc.objects[id].size;
        uint32_t offset = desc.layers[n].offset[0];
        struct pl_fmt *fmt;

        if (fd == -1) {
            printf("Fehler beim Import von Surface %d\n", index);
            return;
        }

        if (decoder->PixFmt == AV_PIX_FMT_NV12) {
            fmt = pl_find_named_fmt(p->gpu, n == 0 ? "r8" : "rg8"); // 8 Bit YUV
        } else {
            fmt = pl_find_named_fmt(p->gpu, n == 0 ? "r16" : "rg16");   // 10 Bit YUV
        }
        
        fmt->fourcc = desc.layers[n].drm_format;
 
       struct pl_tex_params tex_params = {
            .w = n == 0 ? image_width : image_width / 2, 
            .h = n == 0 ? image_height : image_height / 2,
            .d = 0,
            .format = fmt,
            .sampleable = true,
            .host_writable = false,
            .blit_dst = true,
            .renderable = true,
            .address_mode = PL_TEX_ADDRESS_CLAMP ,
            .sample_mode = PL_TEX_SAMPLE_LINEAR,
            .import_handle = PL_HANDLE_DMA_BUF,
            .shared_mem = (struct pl_shared_mem) {
                    .handle = {
                            .fd = fd,
                        },
                    .size = size,
                    .offset = offset,
		    .stride_h = n == 0 ? image_height : image_height / 2,
                    .stride_w = desc.layers[n].pitch[0],
		    .drm_format_mod = DRM_FORMAT_MOD_INVALID,  // <------------------------    what to use here
                },
        };

       decoder->pl_frames[index].planes[n].texture = pl_tex_create(p->gpu, &tex_params);

    }
    Unlock_and_NoContext;
}

**Comment by haasn** [comment]
You should be setting it to `desc.objects[id].drm_format_modifier`. Does that fix it?

**Comment by haasn** [comment]
By the way, you should be able to get the right `pl_fmt` using `pl_find_fourcc(p->gpu,desc.layers[n].drm_format)`. That way you don't have to hardcode rg8/rg16.

**Comment by jojo61** [comment]
When setting `desc.objects[id].drm_format_modifier`  then the Y plane comes with fourcc "R8" will work and the format modifier is 2

But with the UV Plane the fourcc comes as "GR88" and it will work also with format modifier 2. But the check_mod in gpu.c:518 fails for rg8. When I disable the check_mod then it works fine. 

Also `pl_find_fourcc` will not find a valid format for "GR88".

**Comment by haasn** [comment]
Huh. Why does "rg8" work at all if the texture itself is in format GR88? Wouldn't that result in swapped colors?

**Comment by jojo61** [comment]
No the colors are fine. Maybe the fourcc is wrongly set from ffmpeg

**Comment by haasn** [comment]
Hmm. That's worrying. It's possible the intel driver internally treats RG8 and GR8 as the same thing, though. Still, it leaves an open question regarding what the correct path forwards is. My ideas:

1. Make the `check_mod` into a warning rather than an error. Probably still annoying though, so I don't think this is a good solution.
2. Remove the `check_mod` entirely and just rely on the user getting it right. Uncomfortable with this, because I think it catches legitimate bugs (e.g. users not setting the modifiers exported by vaapi, as you did initially).
3. Introduce a new format "gr8" that is otherwise identical to "rg8" (but host-opaque) and serves only to map to the GR88 fourcc rather than the RG88 fourcc. This would probably solve both of your issues?

**Comment by haasn** [comment]
Btw, in case you haven't seen, `<libplacebo/utils/libav.h>` exists and contains a lot of helpers that could make your life easier (and fix some bugs I noticed in your code), specifically `pl_frame_from_avframe` to set all of the colorspace metadata etc. correctly.

**Comment by jojo61** [comment]
Yes I have played with this function. But I preallocate the textures in my design and `pl_frame_from_avframe` creates its own textures, so I can not use it strait forward. I have copied some parts of it into my driver. Also you do not catch all failures from ffmpeg where the wrong colorcodes come. 

I would prefer if `check_mod` would just warn once and not fail until further investigation.

**Comment by haasn** [comment]
To clarify, `pl_frame_from_avframe` does *not* create textures. It only sets all of the non-texture metadata. So you can preallocate textures and use `pl_frame_from_avframe` at the same time.

(`pl_frame_recreate_from_avframe` is what (re)creates textures, but it's impractical for your use case because you need to map frames anyway)

> I would prefer if `check_mod` would just warn once and not fail until further investigation.

I suppose this is a reasonable compromise for the transition period at the very least. That way I have enough time to investigate and fix such bugs without it causing regressions.

**Comment by haasn** [comment]
> Also you do not catch all failures from ffmpeg where the wrong colorcodes come.

Which ones? Can you open an issue for this?

**Comment by haasn** [comment]
@jojo61 I think this change is causing lots of issues for users, specifically https://github.com/mpv-player/mpv/issues/8702, https://github.com/mpv-player/mpv/issues/8668 and https://github.com/haasn/libplacebo/issues/98.

You'll notice the error is printed in all of these cases, and would have caught those failures properly. As such, I'm going to revert this change. Please reopen if the issue is still happening for you and we can find a better solution.

**Comment by haasn** [comment]
@jojo61 I think your issue is fixed by instead always adding INVALID to the drm format modifier list in OpenGL. I've pushed this to master. (Is this an issue for you under Vulkan?)
