### ISSUE TITLE
libav.h  Issues

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#94]
As mentioned yesterday there where some issue I had with `pl_frame_from_avframe`
 I tested with cuvid decoder and I had to fixup some colorcodes coming from ffmpeg:

    color = frame->colorspace;
    if (color == AVCOL_SPC_UNSPECIFIED) // if unknown
        color = AVCOL_SPC_BT709;
	if (color == AVCOL_SPC_RGB)
		color = AVCOL_SPC_BT470BG;  // fix ffmpeg libav failure
	frame->colorspace = color;
	// more libav fixes
	if (frame->color_primaries == AVCOL_PRI_UNSPECIFIED)
		frame->color_primaries = AVCOL_PRI_BT709;
	if (frame->color_trc == AVCOL_TRC_UNSPECIFIED)
		frame->color_trc = AVCOL_TRC_BT709;

This is not a failure of your lib but it needs a fixing somewhere.

I use prelocated pl_frames with already allocated planes/textures. After using your function the plane Pointers are gone. 
I had to save/restore them before using your function;

ffmpeg reports HDR_HLG as `AVCOL_SPC_BT2020_NCL`  and this is not  properly setup as HLG in the pl_frame. I do not remember exactly what the reason for this was. I think the eotf was not set correct.

This where only tests with a cuvid decoder from ffmpeg. With vaapi it may be different and the colorsettings maybe better in ffmpeg.  Actually this should be fixed in ffmepg, but I do not want to wait for this.

One more thing. With libplacebo-opengl  the picture is upside down and I need to fix this with switching  the crop Parameter for y0 an y1. This is not handled in your function ether.

**Comment by haasn** [comment]
> This is not a failure of your lib but it needs a fixing somewhere.

`AVCOL_SPC_UNSPECIFIED` is already handled appropriately:

```
    } else if (!out->repr.sys) {

        // libav* likes leaving this as UNKNOWN for YCbCr frames, which
        // confuses libplacebo since we infer UNKNOWN as RGB. To get around
        // this, explicitly infer a suitable colorspace for non-RGB formats.
        out->repr.sys = pl_color_system_guess_ycbcr(frame->width, frame->height);
    }
```

For `AVCOL_SPC_RGB`, the issue is that `AVCOL_SPC_RGB` being combined with a non-RGB pixdesc? What component is doing this? Do you have an example of an AVFrame that has this issue?

For `AVCOL_PRI/TRC_UNSPECIFIED`, libplacebo translates those to `PL_COLOR_PRIM/TRC_UNKNOWN`, which get inferred based on the color system elsewhere in the libplacebo pipeline. If there's a bug in that inference logic, the AVFrame layer is not the correct place to fix it. What issues were you having with the existing code?

> I use prelocated pl_frames with already allocated planes/textures. After using your function the plane Pointers are gone.

Ah, yes - libplacebo is still based on the design that `pl_frame` is not really meant to be persistent. It's possible we could fix this by having it explicitly preserve the texture pointers, but I think it's less surprising for all of the `pl_frame` initialization functions to explicitly initialize the entire struct.

If you have pre-initialized textures you could actually use `pl_frame_recreate_from_avframe` which will re-use those textures (as long as the size etc. still matches). But otherwise, just set the plane textures explicitly after the call to `pl_frame_from_avframe`.

> With libplacebo-opengl the picture is upside down and I need to fix this with switching the crop Parameter for y0 an y1.

I don't think this is the correct place to do that either. The correct place would be to adjust it for the render target. `pl_frame_from_swapchain` does this already:

```
    if (frame->flipped)
        PL_SWAP(out_frame->crop.y0, out_frame->crop.y1);
```

Does this not work for you?
