### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by jojo61** [haasn/libplacebo#99]
#include <libplacebo/filters.h>

Results in the following failure:

g++ -g -O3  -Werror=overloaded-virtual -Wno-parentheses -Wdeclaration-after-statement -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -I/usr/include -I/usr/src/vdr/vdr-2.4.6/include -I/usr/include/alsa -I/usr/local/include -I/usr/include/libdrm -I/usr/include/freetype2    -I/usr/local/include  -I/usr/local/include -I./opengl -I./ -DPLUGIN_NAME_I18N='"softhdcuvid"' -D_GNU_SOURCE -DDEBUG            -DHAVE_GL          -DAV_INFO -DAV_INFO_TIME=3000    -DUSE_MPEG_COMPLETE             -DH264_EOS_TRICKSPEED           -DUSE_VDR_SPU                   -DUSE_ALSA -DUSE_OSS -DUSE_OPENGLOSD -DUSE_GLX -DPLACEBO -DCUVID                        -DUSE_SCREENSAVER -DUSE_SWRESAMPLE   -g  -W -Wextra -Winit-self -Werror=overloaded-virtual  -Wno-unused-parameter    -c -o softhdcuvid.o softhdcuvid.cpp
cc1plus: warning: command line option ‘-Wdeclaration-after-statement’ is valid for C/ObjC but not for C++
In file included from /usr/local/include/libplacebo/filters.h:22:0,
                 from softhdcuvid.cpp:55:
/usr/local/include/libplacebo/log.h:56:4: error: conflicting declaration ‘typedef const struct pl_log* pl_log’
 } *pl_log;
    ^~~~~~
/usr/local/include/libplacebo/log.h:54:22: note: previous declaration as ‘struct pl_log’
 typedef const struct pl_log {
                      ^~~~~~
/usr/local/include/libplacebo/log.h: In function ‘pl_log* pl_context_create(int, const pl_log_params*)’:
/usr/local/include/libplacebo/log.h:108:63: error: invalid cast from type ‘pl_log’ to type ‘pl_log*’
     return (struct pl_context *) pl_log_create(api_ver, params);
                                                               ^
/usr/local/include/libplacebo/log.h: In function ‘void pl_context_update(pl_log*, const pl_log_params*)’:
/usr/local/include/libplacebo/log.h:119:28: error: no matching function for call to ‘pl_log::pl_log(pl_log*&)’
     pl_log_update((pl_log) ctx, params);
                            ^~~
/usr/local/include/libplacebo/log.h:54:22: note: candidate: pl_log::pl_log()
 typedef const struct pl_log {
                      ^~~~~~
/usr/local/include/libplacebo/log.h:54:22: note:   candidate expects 0 arguments, 1 provided
/usr/local/include/libplacebo/log.h:54:22: note: candidate: constexpr pl_log::pl_log(const pl_log&)
/usr/local/include/libplacebo/log.h:54:22: note:   no known conversion for argument 1 from ‘pl_log*’ to ‘const pl_log&’
/usr/local/include/libplacebo/log.h:54:22: note: candidate: constexpr pl_log::pl_log(pl_log&&)
/usr/local/include/libplacebo/log.h:54:22: note:   no known conversion for argument 1 from ‘pl_log*’ to ‘pl_log&&’
In file included from softhdcuvid.cpp:55:0:
/usr/local/include/libplacebo/filters.h: At global scope:
/usr/local/include/libplacebo/filters.h:322:4: error: conflicting declaration ‘typedef const struct pl_filter* pl_filter’
 } *pl_filter;
    ^~~~~~~~~
/usr/local/include/libplacebo/filters.h:279:22: note: previous declaration as ‘struct pl_filter’
 typedef const struct pl_filter {
                      ^~~~~~~~~
make: *** [<eingebaut>: softhdcuvid.o] Fehler 1

**Comment by haasn** [comment]
How do I reproduce this? It works for me, even with `g++`.

**Comment by jojo61** [comment]
All I do is just include filters.h   Nothing else.

**Comment by haasn** [comment]
Oh, my mistake. I can reproduce it now.

**Comment by haasn** [comment]
This is a tough one. In C++, `typedef struct pl_log *pl_log` is invalid. The only solutions I can see is to rename either the struct or the typedef, or make the typedef a non-pointer.

* Renaming the struct would break all existing code in a horrifically backwards incompatible way, and is definitely out.
* Renaming the typedef would break new (libplacebo-4.x) code, but not much new code is written. That said, having more verbose identifiers for the rest of eternity due to a historical accident is annoying.
* Making the typedef a non-pointer would break all new code in a more subtle way and is not something I'm terribly happy about.

**Comment by haasn** [comment]
I think I'm in favor of renaming the structs, since I want to move to the new libplacebo-4 coding style in general. But, to minimize breaking backwards compatibility, I will alias the new names to the old names `__cplusplus` is undefined.

This would break all C++ users but leave C code untouched. Meaning you would have to switch over to the new coding style (typedef'd object names). I guess that's a reasonable compromise.
